# Generated by Django 3.2.9 on 2021-11-11 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0005_visitorlog_status_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="maximum_visits",
            field=models.IntegerField(
                blank=True,
                help_text="If set, defines the maximum number of times the link can be used.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="visits_count",
            field=models.IntegerField(
                default=0, help_text="The current number of times a link has been used."
            ),
        ),
    ]
